name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to server
      run: |
        ssh root@92.112.192.183 '
          cd /app/PawMed &&
          git remote set-url origin git@github.com:Doxteur/pawmed.git &&
          git pull &&
          docker compose up -d --build
        '
